### ISSUE TITLE
Any way to add the mime type to a compose object

### ISSUE THREAD

**Issue by safwaan-menk** [yoshidan/google-cloud-rust#87]
Looking at the compose.rs, I see the build function doesn't give us the ability to specify a mime type. According th the google documentation, the mime type should be the type of the first object if not set, but this is not showing on the cloud console. Can you add the ability to specify a mime type?

```
pub(crate) fn build(base_url: &str, client: &Client, req: &ComposeObjectRequest) -> RequestBuilder {
    let url = format!(
        "{}/b/{}/o/{}/compose",
        base_url,
        req.bucket.escape(),
        req.destination_object.escape()
    );
    let builder = client.post(url).query(&req).json(&req.composing_targets);
    if let Some(e) = &req.encryption {
        e.with_headers(builder)
    } else {
        builder
    }
}
```

**Comment by yoshidan** [comment]
You can set mime type in `ComposeObjectRequest.composing_targets.destination.content_type` 

https://cloud.google.com/storage/docs/json_api/v1/objects/compose#request-body
https://cloud.google.com/storage/docs/json_api/v1/objects#resource-representations

It works with the sample code below.
However, currently `storage_class` is required and `Object` doesn't implement the `Default` trait, so all properties must be specified.
Since it is very inconvenient, I will modify the implementation for this.
```
client.compose_object(
                &ComposeObjectRequest {
                    bucket: bucket_name.to_string(),
                    destination_object: format!("{}_composed", uploaded.name),
                    destination_predefined_acl: None,
                    composing_targets: ComposingTargets {
                        destination: Some(Object {
                            content_type: Some("image/jpeg".to_string()),                           
                            storage_class: "STANDARD".to_string(),
                           // ... 
                        }),
                        source_objects: vec![SourceObjects {
                            name: format!("{}_rewrite", uploaded.name),
                            ..Default::default()
                        }],
                    },
                    ..Default::default()
                },
                None,
            )
            .await
            .unwrap();
```
<img width="926" alt="スクリーンショット 2022-12-27 11 29 05" src="https://user-images.githubusercontent.com/958174/209601614-29b3241a-8bde-41a8-9025-8e201e5d8017.png">
